import { Inter } from 'next/font/google'
import './custom.css'
import 'bootstrap/dist/css/bootstrap.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import './css/dashboard.css';

import PartHeader from './parts/PartHeader';
import PartSidebar from './parts/PartSidebar';
import ImportBS from './ImportJS/ImportBS';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const viewport = {
  themeColor: '#712cf9',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <ImportBS />
      <body className={inter.className}>
        <PartHeader/>
        <div className="container-fluid">
          <div className="row">
            <PartSidebar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
